### PR TITLE
Extra features

### PR DESCRIPTION
**Pull request by pieper126**
Adds the following support for the Creditsafe api:
* get_portfolios
* create_portfolio
* get_portfolio_monitoring_rules
* get_supported_change_events
* set_portfolio_monitoring_rules
* add_companies_to_portfolios
* remove_companies_from_portfolios
* list_monitored_companies
* set_default_changes_check_period

### CODE REVIEW

**Comment by timrogers** [comment]
Let me know when this is in a state where you'd like it reviewed :smile: @pieper126 !

**Comment by pieper126** [comment]
@timrogers, the pull request should be ready for review!

**Comment by hmac** [comment]
@pieper126 sorry for the radio silence - this looks great! If you're willing to rebase it then I'm happy to review and merge 😄

**Comment by claudiosv** [comment]
@timrogers @hmac Would you folks be interested in reviewing this again if it's rebased?

**Comment by hmac** [comment]
@claudiosv I no longer work at GC so I'm not best placed to answer I'm afraid - @gflandre @keylorch is this one for you guys?

**Comment by keylorch** [comment]
Hi @claudiosv! Sure, we'd be happy to review it once it is ready! 

(thanks @hmac!)

**Comment by claudiosv** [comment]
Hi @keylorch , I've created #106 as a continuation of this PR.

**Pull request closed without merging**
